import test from 'node:test';
import assert from 'node:assert/strict';
import { evaluateTradingRadar } from '../scripts/radar/trading-radar.mjs';
const NOW = new Date('2026-07-23T10:00:00Z').getTime();
const BTC = { symbol: 'BTCUSDT', baseAsset: 'BTC', quoteAsset: 'USDT', status: 'TRADING', quoteVolume24h: 900e6, bidPrice: 70000, askPrice: 70007, spreadPct: 0.01, change24hPct: 1.2 };
const ETH = { symbol: 'ETHUSDT', baseAsset: 'ETH', quoteAsset: 'USDT', status: 'TRADING', quoteVolume24h: 600e6, bidPrice: 3600, askPrice: 3601, spreadPct: 0.03, change24hPct: 0.8 };
const candidate = { symbol: 'LOCALUSDT', baseAsset: 'LOCAL', quoteAsset: 'USDT', status: 'TRADING', quoteVolume24h: 250e6, bidPrice: 140, askPrice: 140.04, change24hPct: -9.5, volumeSpike: 2.4, atrPct: 4, noNewLowMinutes: 34, rangeFormed: true, sellAggressionFading: true, higherLowHeld: true, reclaimConfirmed: true, flushLow: 132 };
function row(overrides = {}) { return { rollingMeasuredAt: new Date(NOW - 1000).toISOString(), rollingWindowSec: 300, samples: { aggTrades: 60, depthSnapshots: 2, klines: 30 }, source: 'binance-futures-public', validation: { makerFlagsValid: true, tradesValidated: true, tradesSorted: true, klinesValidated: true }, absorptionScore: 84, bidDepthRebuildPct: 20, aggressiveSellsFailed: true, deltaImprovementPct: 70, marketBuyVolumeDominance: 0.43, supportRetestHeld: true, spreadAndSlippageHealthy: true, spreadPct: 0.03, depthUsdWithin1Pct: 1800000, marketSellRatio: 0.57, flow: { cumulativeDeltaPct: 70, takerBuySellRatio: 0.75, aggressiveSellExhaustion: true }, ...overrides }; }
function state(rollingRow) { return evaluateTradingRadar({ markets: [BTC, ETH, candidate], source: 'local-measurement-test', now: NOW, rollingMicrostructureSnapshot: { provider: 'local-rolling-measured', updatedAtMs: NOW, trusted: true, data: { LOCALUSDT: rollingRow } } }); }
test('complete local trusted rolling row reaches the existing strict Absorb gate, without self-authorizing Telegram', () => { const c = state(row()).candidates.find((item) => item.symbol === 'LOCALUSDT'); assert.equal(c.ABSORB_MODE, 'STRICT'); assert.equal(c.STRICT_ABSORB_CONFIRMED, true); assert.notEqual(c.STATUS, 'AGGRESSIVE_ENTRY_READY'); assert.equal(c.telegramEligible, false); });
test('stale, thin, malformed, untrusted, or incomplete local rows cannot activate strict Absorb', () => { const cases = [row({ rollingMeasuredAt: new Date(NOW - 11 * 60 * 1000).toISOString() }), row({ samples: { aggTrades: 9, depthSnapshots: 2, klines: 30 } }), row({ validation: { makerFlagsValid: false, tradesValidated: true, tradesSorted: true, klinesValidated: true } }), row({ marketBuyVolumeDominance: undefined })]; for (const value of cases) { const c = state(value).candidates.find((item) => item.symbol === 'LOCALUSDT'); assert.equal(c.STRICT_ABSORB_CONFIRMED, false); assert.notEqual(c.STATUS, 'AGGRESSIVE_ENTRY_READY'); assert.equal(c.telegramEligible, false); } });